springdoc:
  swagger-ui:
      path: /api/index.html
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  group-configs:
    - group: v1
      paths-to-match:
        - /api/v1/**
server:
  error:
    include-stacktrace: never
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://admin.spring-boot-admin.svc.cluster.local:8080
        instance:
          management-url: http://library.library.svc.cluster.local:8080/actuator
          health-url: http://library.library.svc.cluster.local:8080/actuator/health
          service-url: https://api.library.mikhailov.net
  application:
    name: library-api

