springdoc:
    swagger-ui:
      urls:
        - url: /api/v1/api
          name: original
      path: /api/index.html
      config-url: /v3/api-docs/swagger-config
    api-docs:
      enabled: false
server:
  error:
    include-stacktrace: never
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://admin.spring-boot-admin.svc.cluster.local:8080
        instance:
          management-url: http://library.library.svc.cluster.local:8080/actuator
          health-url: http://library.library.svc.cluster.local:8080/actuator/health
          service-url: https://api.library.mikhailov.net
  application:
    name: library-api

