springdoc:
    swagger-ui:
      urls:
        - url: /api
          name: original
      path: /swagger-ui
      config-url: /v3/api-docs/swagger-config
      use-root-path: true
    api-docs:
      enabled: false
server:
  error:
    include-stacktrace: never

