springdoc:
    swagger-ui:
      urls:
        - url: /api/v1/api
          name: original
      path: /api/v1/swagger-ui
      config-url: /v3/api-docs/swagger-config
    api-docs:
      enabled: false
server:
  error:
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - liquebase

