---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-m2-cache
    image: plugins/s3-cache
    pull: if-not-exists
    failure: ignore
    settings:
      pull: true
      path: cache
      filename: project-books-m2.tar
      endpoint: http://s3-minio.gitlab.svc.cluster.local:9000
      workdir: m2
      access_key:
        from_secret: S3AccessKey
      secret_key:
        from_secret: S3SecretKey
      restore: true

  - name: build
    image: quay.io/testcontainers/dind-drone-plugin
    environment:
      TESTCONTAINERS_RYUK_DISABLED: true
      CI_WORKSPACE: "/drone/src"
    settings:
      # This specifies the command that should be executed to perform build, test and
      #  integration tests. Not to be confused with Drone's `command`:
      cmd: sleep 5 && mvn clean verify -Dmaven.repo.local=m2
      # This image will run the cmd with your build steps
      build_image: maven:3.8.6-openjdk-18
      # Not mandatory; enables pre-fetching of images in parallel with the build, so may save
      #  time:
      prefetch_images:
        - "postgres:13-alpine"
    volumes:
      - name: dockersock
        path: /var/run

  - name: rebuild-m2-cache
    image: plugins/s3-cache
    pull: if-not-exists
    failure: ignore
    settings:
      rebuild: true
      path: cache
      filename: project-books-m2.tar
      endpoint: http://s3-minio.gitlab.svc.cluster.local:9000
      workdir: m2
      mount: m2
      access_key:
        from_secret: S3AccessKey
      secret_key:
        from_secret: S3SecretKey

  - name: build-image
    image: docker:17
    pull: if-not-exists
    environment:
      DOCKER_HOST: tcp://drone-docker.droneci.svc.cluster.local:2375
      DOCKER_TLS_CERTDIR: ""
    when:
      branch:
        - master
    commands:
      - cd library
      - docker image build -f Dockerfile -t registry-http.registry.svc.cluster.local/library:${CI_COMMIT_SHA} .
      - docker push registry-http.registry.svc.cluster.local/library:${CI_COMMIT_SHA}

  - name: deploy
    image: bitnami/kubectl:1.24
    pull: if-not-exists
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
    environment:
      K8S_TOKEN:
        from_secret: k8sToken
    commands:
      - kubectl config set-cluster "k8s.mikhailov.net" --server=https://192.168.0.5:6443  --insecure-skip-tls-verify
      - kubectl config set-credentials user --token=$K8S_TOKEN
      - kubectl config set-context "local" --cluster="k8s.mikhailov.net" --user="user"
      - kubectl config use-context "local"
      - kubectl config set-context --current --namespace=library
      - kubectl set image deployment/library library=registry-http.registry.svc.cluster.local/library:${CI_COMMIT_SHA}

services:
  - name: docker
    image: registry.mikhailov.net/dindwithopts:23
    privileged: true
    environment:
      DOCKER_OPTS: "--registry-mirror http://registry-mirror-http.registry.svc.cluster.local --insecure-registry registry-http.registry.svc.cluster.local --insecure-registry registry-mirror-http.registry.svc.cluster.local --mtu 1400"
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: bitnami/kubectl:1.24
    pull: if-not-exists
    when:
      branch:
        - master
    environment:
      K8S_TOKEN:
        from_secret: k8sToken
    commands:
      - kubectl config set-cluster "k8s.mikhailov.net" --server=https://192.168.0.5:6443  --insecure-skip-tls-verify
      - kubectl config set-credentials user --token=$K8S_TOKEN
      - kubectl config set-context "local" --cluster="k8s.mikhailov.net" --user="user"
      - kubectl config use-context "local"
      - kubectl config set-context --current --namespace=library
      - kubectl set image deployment/library library=registry-http.registry.svc.cluster.local/library:${CI_COMMIT_SHA}

trigger:
  event:
    - promote
  target:
    - production
