cache:
  key: maven
  paths:
    - $CI_PROJECT_DIR/.m2/repository

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_TLS_CERTDIR: ""
  TESTCONTAINERS_HOST_OVERRIDE: "localhost"


services:
  - name: docker:dind

stages:
  - build
  - deploy

build-job:
  image: maven:3.8.6-openjdk-18
  stage: build
  script:
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository clean verify
