cache:
  key: maven
  paths:
    - $CI_PROJECT_DIR/.m2/repository

services:
  - name: docker:dind

stages:
  - test
  - build
  - deploy

junit:
  extends: [.docker]
  artifacts:
    paths:
      - "*/target/*-spring-boot.jar"
  image: maven:3.8.6-openjdk-18
  stage: test
  script:
    - mvn clean verify -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

push to registry:
  extends: [.docker]
  image: docker:latest
  stage: build
  script:
    - cd library
    - sleep 2
    - docker image build -f Dockerfile -t registry.mikhailov.net/library:latest .
    - docker push registry.mikhailov.net/library:latest


.docker:
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    TESTCONTAINERS_HOST_OVERRIDE: "localhost"
