cache:
  key: maven
  paths:
    - $CI_PROJECT_DIR/.m2/repository

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_TLS_CERTDIR: ""
  TESTCONTAINERS_HOST_OVERRIDE: "localhost"


services:
  - name: docker:dind

stages:
  - test
  - build
  - deploy

junit:
  image: maven:3.8.6-openjdk-18
  stage: test
  script:
    - mvn clean verify -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

push to registry:
  image: maven:3.8.6-openjdk-18
  stage: build
  script:
    - mvn clean spring-boot:build-image -DskipTests -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
