cache:
  key: maven
  paths:
    - $CI_PROJECT_DIR/.m2/repository

services:
  - name: docker:dind

stages:
  - test
  - build
  - deploy

junit:
  extends: [ .docker ]
  artifacts:
    paths:
      - "*/target/*-spring-boot.jar"
  image:
    name: maven:3.8.6-openjdk-18
    pull_policy: if-not-present
  stage: test
  script:
    - mvn clean verify -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

push to registry:
  extends: [ .docker ]
  image:
    name: docker:latest
    pull_policy: if-not-present
  stage: build
  script:
    - cd library
    - sleep 4
    - docker image build -f Dockerfile -t registry.mikhailov.net/library:latest .
    - docker push registry.mikhailov.net/library:latest

deploy to kubernetes:
  image:
    name: bitnami/kubectl:1.24
    pull_policy: if-not-present
  stage: deploy
  variables:
    K8S_TOKEN: $K8S_TOKEN
  script:
    - kubectl config set-cluster "k8s.mikhailov.net" --server=https://192.168.0.5:6443  --insecure-skip-tls-verify
    - kubectl config set-credentials user --token=$K8S_TOKEN
    - kubectl config set-context "local" --cluster="k8s.mikhailov.net" --user="user"
    - kubectl config use-context "local"
    - kubectl config set-context --current --namespace=library
    - kubectl rollout restart deployment library

.docker:
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    TESTCONTAINERS_HOST_OVERRIDE: "localhost"
